// <auto-generated />
using System;
using JunoBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JunoBE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("JunoBE.Features.Address.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyEntityId")
                        .IsUnique();

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("JunoBE.Features.Properties.PropertyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("homeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("homeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("square_meters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("JunoBE.Features.Address.AddressEntity", b =>
                {
                    b.HasOne("JunoBE.Features.Properties.PropertyEntity", "property")
                        .WithOne("address")
                        .HasForeignKey("JunoBE.Features.Address.AddressEntity", "PropertyEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("property");
                });

            modelBuilder.Entity("JunoBE.Features.Properties.PropertyEntity", b =>
                {
                    b.Navigation("address");
                });
#pragma warning restore 612, 618
        }
    }
}
