version: '1'

services:
  db:
    container_name: junoDB
    restart: always
    image: postgres:16.10-alpine3.21
    ports:
      - 5432:5432
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  